using DtsDevChallenge.Common;
using Microsoft.AspNetCore.JsonPatch.SystemTextJson;
using Microsoft.EntityFrameworkCore;

namespace DtsDevChallenge.Backend.Data;

/// <summary>
/// Task repository backed by a database via EF Core
/// </summary>
public class DbContextTaskRepository(TaskDbContext db): ITaskRepository
{
    /// <inheritdoc />
    public async ValueTask<TaskItem[]> GetTasks(uint page = 0, uint pageSize = 10)
    {
        return await db.Tasks
            .OrderBy(t => t.Id)
            .Skip((int)(page * pageSize))
            .Take((int)pageSize)
            .ToArrayAsync();
    }

    /// <inheritdoc />
    public async ValueTask<TaskItem> CreateTaskItem(string title, string? description, DateTimeOffset dueBy, TaskItemStatus itemStatus)
    {
        var item = new TaskItem(
            0, // ID will be generated by the database
            title,
            description,
            dueBy,
            itemStatus
        );
        db.Tasks.Add(item);
        await db.SaveChangesAsync();
        return item;
    }

    /// <inheritdoc />
    public ValueTask<TaskItem?> GetTaskItem(int id)
    {
        return db.Tasks.FindAsync(id);
    }

    /// <inheritdoc />
    public async ValueTask DeleteTaskItem(int id)
    {
        var item = await GetTaskItem(id);

        if (item == null)
        {
            throw new KeyNotFoundException($"Task with ID '{id}' does not exist");
        }
        
        db.Tasks.Remove(item);
        await db.SaveChangesAsync();
    }

    /// <inheritdoc />
    public async ValueTask<TaskItem> ModifyTaskItem(int id, JsonPatchDocument<TaskItem> patchDoc)
    {
        var item = await GetTaskItem(id);
        if (item == null)
        {
            throw new KeyNotFoundException($"Task with ID '{id}' does not exist");
        }

        patchDoc.ApplyTo(item);
        await db.SaveChangesAsync();

        return item;
    }
}